# Generated by Django 3.1.1 on 2020-10-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=60)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.CharField(blank=True, max_length=1000)),
                ('thumbnail', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('ext_name', models.CharField(max_length=150)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_players.images')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('ign', models.CharField(max_length=200, verbose_name='In Game Name')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi_players.country')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_players.images')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_score', models.IntegerField()),
                ('taam_2_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.DecimalField(blank=True, decimal_places=13, max_digits=16)),
                ('assists', models.DecimalField(blank=True, decimal_places=13, max_digits=16)),
                ('flash_assists', models.DecimalField(blank=True, decimal_places=13, max_digits=16)),
                ('death', models.DecimalField(blank=True, decimal_places=13, max_digits=16)),
                ('dmg_give', models.DecimalField(blank=True, decimal_places=13, max_digits=18)),
                ('dmg_taken', models.DecimalField(blank=True, decimal_places=13, max_digits=18)),
                ('history', models.IntegerField(blank=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=13, max_digits=14)),
                ('plant', models.DecimalField(blank=True, decimal_places=13, max_digits=16)),
                ('defuse', models.DecimalField(blank=True, decimal_places=13, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi_players.country')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_players.images')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('tier', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True)),
                ('short_title', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='esi_players.team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='esi_players.team')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('tier', models.IntegerField()),
                ('best_of', models.IntegerField()),
                ('postponed_from', models.DateTimeField(blank=True)),
                ('forfeit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forfeit', to='esi_players.scores')),
                ('scores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='esi_players.scores')),
                ('teams', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi_players.teams')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi_players.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_players.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_players.stats'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_stats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ct_stats', to='esi_players.stats')),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi_players.map')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi_players.player')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi_players.series')),
                ('t_stats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t_stats', to='esi_players.stats')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi_players.images'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi_players.region'),
        ),
    ]
