# Generated by Django 3.1.1 on 2020-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='default',
            field=models.CharField(default='https://img.abiosgaming.com/other/New-Abios-Place-Holder.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='images',
            name='thumbnail',
            field=models.CharField(default='https://img.abiosgaming.com/other/thumbnails/New-Abios-Place-Holder.png', max_length=1000),
        ),
    ]
