# Generated by Django 3.1.1 on 2020-10-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esi_players', '0002_auto_20201004_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='ext_name',
        ),
    ]
