# Generated by Django 3.1.1 on 2020-10-04 12:48

from django.db import migrations
from django.db import IntegrityError, transaction
from esi_players.models import Player, Team, Images , PlayerTeam, Region, Country, Map, Tournament
import json


def add_regions(apps, schema_editor):
    try:
        with transaction.atomic():
            with open("esi_players/data/regions.json") as json_file:
                regions = json.load(json_file)
                for r in regions:
                    region = Region()
                    region.region_id = r['id']
                    region.name = r['name']
                    region.short_name = r['short_name']
                    region.save()
    except IntegrityError:
        raise IntegrityError("Region Error")


def add_countries(apps, schema_editor):
    try:
        with transaction.atomic():
            with open("esi_players/data/countries.json") as json_file:
                countries = json.load(json_file)
                for c in countries:
                    country = Country()
                    country.country_id = c['id']
                    country.name = c['name']
                    country.short_name = c['short_name']
                    imgs = Images()
                    imgs.default = c['images']['default']
                    imgs.thumbnail = c['images']['thumbnail']
                    imgs.save()
                    country.images = imgs
                    country.region = Region.objects.get(region_id=c['region'])
                    country.save()
    except IntegrityError:
        raise IntegrityError("Country Error")


def add_maps(apps, schema_editor):
    try:
        with transaction.atomic():
            with open("esi_players/data/maps.json") as json_file:
                maps = json.load(json_file)
                for m in maps:
                    map_ = Map()
                    map_.map_id = m['id']
                    map_.name = m['name']
                    imgs=Images()
                    imgs.save()
                    map_.images = imgs
                    map_.save()
    except IntegrityError:
        raise IntegrityError("Map Error")


class Migration(migrations.Migration):

    dependencies = [
        ('esi_players', '0003_remove_map_ext_name'),
    ]

    operations = [
        migrations.RunPython(add_regions),
        migrations.RunPython(add_countries),
        migrations.RunPython(add_maps)
    ]
