# Generated by Django 3.1.1 on 2020-10-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esi_players', '0004_auto_20201004_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esi_players.images'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esi_players.stats'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='taam_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='team_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stats',
            name='assists',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stats',
            name='death',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stats',
            name='defuse',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stats',
            name='dmg_give',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stats',
            name='dmg_taken',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stats',
            name='flash_assists',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stats',
            name='history',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='kills',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stats',
            name='plant',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
