# Generated by Django 3.1.1 on 2020-09-25 17:39

from django.db import migrations
from django.db import IntegrityError, transaction
from esi_players.models import Player, Team, PlayerTeam
import json


def add_players(apps, schema_editor):
    try:
        with transaction.atomic():
            with open("esi_players/data/players_list.json") as json_file:
                players = json.load(json_file)
                for p in players:
                    player = Player()
                    player.player_id = p['player_id']
                    player.ign = p['ign']
                    player.first_name = p['first_name']
                    player.last_name = p['last_name']
                    player.thumbnail = p['thumbnail']
                    player.save()
    except IntegrityError:
        raise IntegrityError("Players Fucked Up")


def add_teams(apps, schema_editor):
    try:
        with transaction.atomic():
            with open("esi_players/data/team_list.json") as json_file:
                teams = json.load(json_file)
                for t in teams:
                    team = Team()
                    team.team_id = t['team_id']
                    team.name = t['name']
                    team.save()
    except IntegrityError:
        raise IntegrityError("Teams Fucked Up")


def add_playerteams(apps, schema_editor):
    try:
        with transaction.atomic():
            with open("esi_players/data/playerteam_list.json") as json_file:
                playerteams = json.load(json_file)
                for pt in playerteams:
                    playerteam = PlayerTeam()
                    playerteam.team = Team.objects.get(team_id=int(pt['team']))
                    playerteam.player = Player.objects.get(player_id=int(pt['player']))
                    playerteam.save()
    except IntegrityError:
        raise IntegrityError("Plater Teams Fucked Up")


class Migration(migrations.Migration):

    dependencies = [
        ('esi_players', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_players),
        migrations.RunPython(add_teams),
        migrations.RunPython(add_playerteams)
    ]
