# Generated by Django 3.1.2 on 2020-10-18 12:58

from django.db import migrations, models
import esi_pricingengine.models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_pricingengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[(esi_pricingengine.models.TransactionType['B'], 'Buy'), (esi_pricingengine.models.TransactionType['S'], 'Sell')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
