# Generated by Django 3.1.2 on 2020-10-31 17:00

from django.db import migrations, models
import esi_pricingengine.models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_pricingengine', '0002_auto_20201018_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[(esi_pricingengine.models.TransactionType['B'], 'Buy'), (esi_pricingengine.models.TransactionType['S'], 'Sell')], max_length=255, null=True),
        ),
    ]
